package com.trustlink.backend.entity;

public enum TipoAccionAuditoria {
    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    REGISTRO_USUARIO,
    PRODUCTO_PUBLICADO,
    ORDEN_CREADA,
    ORDEN_ENTREGA_CONFIRMADA,
    ORDEN_DISPUTA_REPORTADA,
    ORDEN_DISPUTA_RESUELTA,
    USUARIO_BANEADO,
    USUARIO_DESBANEADO,
    SOLICITUD_VENDEDOR_CREADA,
    SOLICITUD_VENDEDOR_APROBADA,
    SOLICITUD_VENDEDOR_RECHAZADA,
    SOLICITUD_CREDITO
}
